language: node_js
node_js:
- '10'
cache:
  yarn: true
script:
- yarn lint
- yarn test
before_install:
- cd server
- yarn
env:
  secure: VAa6ZOoEEOcr+eFaxvmkVUL4PIZ14raNUKr5ghRq/Nt6CzXiH2BxLts4jVl1F210xohjkvegs1EiH0JbCXOJe/qN6NZUbuF6bXoYO0iCOJbPOUIPfewpe/SRKwSt1R+l+PahjW3TCjzgTbMJcY0ycI8d+O9uZ2NLKAdb/Uas+d1zH9xvnirT7GTkjGMtGKap0+LPHLhEKO9aLpfMophorv7cv2CmYdumQaxN3SZa0X9Oaq/QFTQOE/ydRAq4gJtV7fSWBFdVTIiG90bTm1G1t6/wXKCnzQQVzGZKe5TctQNiI411Rbyi40QPohTBa8Zn3TWTUQ6AsRajgtJQjg7ljx64Xds4WNq4aRm/n7drSDLCUCrf9A+bhZ//XOp9PLJY6BYHCczIB4kxmN5nTGt4bsJpBS/XP9B3HNeYOx17CgsTihOzT0ksMp6rJOnXxBDpAjr2h3CrLt9jd4JLZqbMqqUaSXcdxwcNi266YvGJd8g12nkuxOM6YwANqEwG3td7z0nD+k1i07fGPr4Fk1X3zXkVkvyeO1AXvNwoajztmO0PW3NtWe4ImGKWSett+EMEhZ8jAjy/qAGdMhHy//fLk1ZP+7vnmd1IZI6AW62NWGfCGB3UdWIkr+gSDtX5uZj8sJlLZEPzTezmWkHZTR131uw+EOBS4BuZAduph+wULeU=
